/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterCaseworkerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.FosterCaseworkerOrganization;
import Business.Organization.Organization;
import static Business.StringConstants.ImmutableStringConstants.*;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BackgroundVerificationWorkRequest;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shahd
 */
public class FosterFamilyMedHistJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FosterCaseWorkerEnterMedicalHistory
     */
    private JPanel userProcessContainer;
    private FosterCaseworkerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private BackgroundVerificationWorkRequest request;
    private Network network;
    
    public FosterFamilyMedHistJPanel(JPanel userProcessContainer, UserAccount account, FosterCaseworkerOrganization organization, Enterprise enterprise, EcoSystem business, BackgroundVerificationWorkRequest backgroundReq, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.request = backgroundReq;
        this.network = network;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbCancer1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cbDiabetes1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        cbHeartDisease1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        cbArthritis1 = new javax.swing.JCheckBox();
        cbAsthama1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbHypertension1 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        cbUlcers1 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        cbTuberculosis1 = new javax.swing.JCheckBox();
        cbHypotension1 = new javax.swing.JCheckBox();
        lblHypo1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        rbYes1 = new javax.swing.JRadioButton();
        rbNo1 = new javax.swing.JRadioButton();
        rbNo2 = new javax.swing.JRadioButton();
        rbYes2 = new javax.swing.JRadioButton();
        rbNo3 = new javax.swing.JRadioButton();
        rbYes3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReason1 = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cbCancer2 = new javax.swing.JCheckBox();
        jLabel39 = new javax.swing.JLabel();
        cbDiabetes2 = new javax.swing.JCheckBox();
        jLabel40 = new javax.swing.JLabel();
        cbHeartDisease2 = new javax.swing.JCheckBox();
        jLabel41 = new javax.swing.JLabel();
        cbArthritis2 = new javax.swing.JCheckBox();
        cbAsthama2 = new javax.swing.JCheckBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        cbHypertension2 = new javax.swing.JCheckBox();
        jLabel44 = new javax.swing.JLabel();
        cbUlcers2 = new javax.swing.JCheckBox();
        jLabel45 = new javax.swing.JLabel();
        cbTuberculosis2 = new javax.swing.JCheckBox();
        cbHypotension2 = new javax.swing.JCheckBox();
        lblHypo = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        rbYes4 = new javax.swing.JRadioButton();
        rbNo4 = new javax.swing.JRadioButton();
        rbNo5 = new javax.swing.JRadioButton();
        rbYes5 = new javax.swing.JRadioButton();
        rbNo6 = new javax.swing.JRadioButton();
        rbYes6 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReason2 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Enter Family's Medical History");

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(850, 440));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 440));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Previously had treatment for serious/chronic illness?");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Previously advised to seek mental health services?");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Previously treated for alchohol/substance abuse?");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("If yes to any of the above please explain reason:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Please select any/all of the existing conditions from below:");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Cancer");

        cbCancer1.setBackground(new java.awt.Color(255, 255, 255));
        cbCancer1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Diabetes");

        cbDiabetes1.setBackground(new java.awt.Color(255, 255, 255));
        cbDiabetes1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Heart Disease");

        cbHeartDisease1.setBackground(new java.awt.Color(255, 255, 255));
        cbHeartDisease1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Arthritis");

        cbArthritis1.setBackground(new java.awt.Color(255, 255, 255));
        cbArthritis1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        cbAsthama1.setBackground(new java.awt.Color(255, 255, 255));
        cbAsthama1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Asthama");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Hypertension");

        cbHypertension1.setBackground(new java.awt.Color(255, 255, 255));
        cbHypertension1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Ulcers");

        cbUlcers1.setBackground(new java.awt.Color(255, 255, 255));
        cbUlcers1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Tuberculosis");

        cbTuberculosis1.setBackground(new java.awt.Color(255, 255, 255));
        cbTuberculosis1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        cbHypotension1.setBackground(new java.awt.Color(255, 255, 255));
        cbHypotension1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        lblHypo1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lblHypo1.setForeground(new java.awt.Color(102, 102, 102));
        lblHypo1.setText("Hypotension");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Basic Details:");

        jLabel31.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Existing Condition(s):");

        btnNext.setBackground(new java.awt.Color(0, 0, 0));
        btnNext.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next>>");
        btnNext.setEnabled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        rbYes1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbYes1);
        rbYes1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbYes1.setForeground(new java.awt.Color(102, 102, 102));
        rbYes1.setText("Yes");

        rbNo1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbNo1);
        rbNo1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbNo1.setForeground(new java.awt.Color(102, 102, 102));
        rbNo1.setText("No");

        rbNo2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbNo2);
        rbNo2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbNo2.setForeground(new java.awt.Color(102, 102, 102));
        rbNo2.setText("No");

        rbYes2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbYes2);
        rbYes2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbYes2.setForeground(new java.awt.Color(102, 102, 102));
        rbYes2.setText("Yes");

        rbNo3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rbNo3);
        rbNo3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbNo3.setForeground(new java.awt.Color(102, 102, 102));
        rbNo3.setText("No");

        rbYes3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rbYes3);
        rbYes3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbYes3.setForeground(new java.awt.Color(102, 102, 102));
        rbYes3.setText("Yes");

        txtReason1.setColumns(20);
        txtReason1.setRows(5);
        jScrollPane1.setViewportView(txtReason1);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNext))
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbDiabetes1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbHeartDisease1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbCancer1)))
                            .addGap(100, 100, 100)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbHypertension1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(47, 47, 47)
                                    .addComponent(cbAsthama1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbArthritis1)))
                            .addGap(100, 100, 100)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblHypo1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbHypotension1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTuberculosis1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbUlcers1))))
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbYes3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbNo3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbYes2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbNo2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbYes1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbNo1)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel7, jLabel8, jLabel9, lblHypo1});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbNo1, rbNo2, rbNo3, rbYes1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbYes1)
                    .addComponent(rbNo1))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbYes2)
                        .addComponent(rbNo2))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbYes3)
                        .addComponent(rbNo3))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbCancer1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cbDiabetes1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cbHeartDisease1)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(cbUlcers1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(cbTuberculosis1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHypo1)
                                .addComponent(cbHypotension1)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(cbArthritis1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(cbAsthama1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(cbHypertension1)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbCancer1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel7, jLabel8, jLabel9, lblHypo1});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbNo1, rbYes1});

        jTabbedPane1.addTab("Parent 1", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 440));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Previously had treatment for serious/chronic illness?");

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("Previously advised to seek mental health services?");

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Previously treated for alchohol/substance abuse?");

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("If yes to any of the above please explain reason:");

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Please select any/all of the existing conditions from below:");

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Cancer");

        cbCancer2.setBackground(new java.awt.Color(255, 255, 255));
        cbCancer2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Diabetes");

        cbDiabetes2.setBackground(new java.awt.Color(255, 255, 255));
        cbDiabetes2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setText("Heart Disease");

        cbHeartDisease2.setBackground(new java.awt.Color(255, 255, 255));
        cbHeartDisease2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel41.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 102, 102));
        jLabel41.setText("Arthritis");

        cbArthritis2.setBackground(new java.awt.Color(255, 255, 255));
        cbArthritis2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        cbAsthama2.setBackground(new java.awt.Color(255, 255, 255));
        cbAsthama2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel42.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(102, 102, 102));
        jLabel42.setText("Asthama");

        jLabel43.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 102, 102));
        jLabel43.setText("Hypertension");

        cbHypertension2.setBackground(new java.awt.Color(255, 255, 255));
        cbHypertension2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel44.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 102, 102));
        jLabel44.setText("Ulcers");

        cbUlcers2.setBackground(new java.awt.Color(255, 255, 255));
        cbUlcers2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel45.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 102, 102));
        jLabel45.setText("Tuberculosis");

        cbTuberculosis2.setBackground(new java.awt.Color(255, 255, 255));
        cbTuberculosis2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        cbHypotension2.setBackground(new java.awt.Color(255, 255, 255));
        cbHypotension2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        lblHypo.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lblHypo.setForeground(new java.awt.Color(102, 102, 102));
        lblHypo.setText("Hypotension");

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 102, 102));
        jLabel46.setText("Basic Details:");

        jLabel47.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 102));
        jLabel47.setText("Existing Condition(s):");

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        rbYes4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(rbYes4);
        rbYes4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbYes4.setForeground(new java.awt.Color(102, 102, 102));
        rbYes4.setText("Yes");

        rbNo4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(rbNo4);
        rbNo4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbNo4.setForeground(new java.awt.Color(102, 102, 102));
        rbNo4.setText("No");

        rbNo5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(rbNo5);
        rbNo5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbNo5.setForeground(new java.awt.Color(102, 102, 102));
        rbNo5.setText("No");

        rbYes5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(rbYes5);
        rbYes5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbYes5.setForeground(new java.awt.Color(102, 102, 102));
        rbYes5.setText("Yes");

        rbNo6.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(rbNo6);
        rbNo6.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbNo6.setForeground(new java.awt.Color(102, 102, 102));
        rbNo6.setText("No");

        rbYes6.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(rbYes6);
        rbYes6.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        rbYes6.setForeground(new java.awt.Color(102, 102, 102));
        rbYes6.setText("Yes");

        txtReason2.setColumns(20);
        txtReason2.setRows(5);
        jScrollPane2.setViewportView(txtReason2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubmit)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbDiabetes2))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbHeartDisease2))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbCancer2)))
                                .addGap(100, 100, 100)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbHypertension2))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addGap(47, 47, 47)
                                        .addComponent(cbAsthama2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbArthritis2)))
                                .addGap(100, 100, 100)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblHypo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbHypotension2))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel45)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbTuberculosis2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbUlcers2))))
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rbYes6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbNo6))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rbYes5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbNo5))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rbYes4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbNo4))))
                            .addComponent(jScrollPane2))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel46)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(rbYes4)
                    .addComponent(rbNo4))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(rbYes5)
                    .addComponent(rbNo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(rbYes6)
                    .addComponent(rbNo6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(cbCancer2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(cbDiabetes2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(cbHeartDisease2)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel44)
                                .addComponent(cbUlcers2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel45)
                                .addComponent(cbTuberculosis2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHypo)
                                .addComponent(cbHypotension2)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel41)
                                .addComponent(cbArthritis2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel42)
                                .addComponent(cbAsthama2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel43)
                                .addComponent(cbHypertension2)))))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Parent 2", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(124, 124, 124))
            .addComponent(jSeparator1)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        if((rbYes4.isSelected()== false && rbNo4.isSelected() == false)||
                (rbYes5.isSelected()== false && rbNo5.isSelected() == false)||
                (rbYes6.isSelected()== false && rbNo6.isSelected() == false)){
            
            JOptionPane.showMessageDialog(null,"Basic Details Cannot be null!!");
            return;
            
        } else if ((rbYes4.isSelected()== true || rbYes5.isSelected()== true || rbYes6.isSelected()== true)
                && txtReason2.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Reason cannot be blank!!");
            return;
    }else{
            if (JOptionPane.showConfirmDialog(null, "Do you want to proceed?", "WARNING",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            setParent2Fileds();
            
            //add doctor work request an case worker work request
        
            request.setSender(userAccount);
            request.setStatus("Sent");
            request.setReceiver(null);
            Organization org = null;
            for(Network net : business.getNetworkList()){
                if(net.equals(network)){
                for(Enterprise enterprise : net.getEnterpriseDirectory().getEnterpriseList()){
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                        if (organization instanceof DoctorOrganization){
                            org = organization;
                            break;
                        }
                    }
                }
                }
            }
            request.setOrgName(org.toString());
            request.setBackgroundCheck(null);
                if (org!=null){
                    org.getWorkQueue().getWorkRequestList().add(request);
                    System.out.println("Added");
                }

                //next
                FosterCaseWorkerManageFamilyJPanel fosterCaseWorkerManageFamilyJPanel = new FosterCaseWorkerManageFamilyJPanel(userProcessContainer, userAccount,  organization,  enterprise,network, business);
                userProcessContainer.add("FosterCaseWorkerManageFamilyJPanel", fosterCaseWorkerManageFamilyJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            } else{
                //do nothing
            }
            
        } 
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if((rbYes1.isSelected()== false && rbNo1.isSelected() == false)||
                (rbYes2.isSelected()== false && rbNo2.isSelected() == false)||
                (rbYes3.isSelected()== false && rbNo3.isSelected() == false)){
            
            JOptionPane.showMessageDialog(null,"Basic Details Cannot be null!!");
            return;
            
        } else if ((rbYes1.isSelected()== true || rbYes2.isSelected()== true || rbYes3.isSelected()== true)
                && (txtReason1.getText().equals(""))){
            JOptionPane.showMessageDialog(null,"Reason cannot be blank!!");
            return;
        }
            else{
            setParent1Fields();
            JOptionPane.showMessageDialog(null, "Parent-1 Medical History saved sucessfull!!");
            btnSave.setEnabled(false);
            btnNext.setEnabled(true);
            rbYes1.setEnabled(false);
            rbYes2.setEnabled(false);
            rbYes3.setEnabled(false);
            rbNo1.setEnabled(false);
            rbNo2.setEnabled(false);
            rbNo3.setEnabled(false);
            cbArthritis1.setEnabled(false);
            cbAsthama1.setEnabled(false);
            cbCancer1.setEnabled(false);
            cbDiabetes1.setEnabled(false);
            cbHeartDisease1.setEnabled(false);
            cbHypertension1.setEnabled(false);
            cbTuberculosis1.setEnabled(false);
            cbUlcers1.setEnabled(false);
            cbHypotension1.setEnabled(false);
            txtReason1.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    public void setParent2Fileds(){
            
        String chronic2 = ""; 
        String alcohol2 = ""; 
        String mental2 = "";
        String cancer2 = "";
        String diabetes2 = "";
        String heartdisease2 = "";
        String arthritis2 = "";
        String asthama2 = "";
        String hypertension2 = "";
        String ulcers2 = "";
        String tuberculosis2 = "";
        String hypotension2 = "";
        
        if(rbYes4.isSelected()){
            chronic2 = "YES";
        }
        if(rbYes5.isSelected()) {
            alcohol2 = "YES";
        }
        if(rbYes6.isSelected()) {
            mental2 = "YES";
        }
        if(rbNo4.isSelected()) chronic2 = "NO";
        if(rbNo5.isSelected()) alcohol2 = "NO";
        if(rbNo6.isSelected()) mental2 = "NO";
        
        
        if(cbCancer2.isSelected()) cancer2 = "CANCER\n";
        if(cbDiabetes2.isSelected()) diabetes2 = "DIABETES\n";
        if(cbHeartDisease2.isSelected()) heartdisease2 = "HEART DISEASE\n";
        if(cbArthritis2.isSelected()) arthritis2 = "ARTHRITIS\n";
        if(cbAsthama2.isSelected()) asthama2 = "ASTHAMA\n";
        if(cbHypertension2.isSelected()) hypertension2 = "HYPERTENSION\n";
        if(cbUlcers2.isSelected()) ulcers2 = "ULCERS\n";
        if(cbTuberculosis2.isSelected())tuberculosis2 = "TUBERCULOSIS\n";
        if(cbHypotension2.isSelected()) hypotension2 = "HYPOTENSION\n";
        
        
    
        Map<String, String> parent2Info = request.getParent2InfoMap();
        parent2Info.put(PARENT2_CHRONIC, chronic2);
        parent2Info.put(PARENT2_MENTAL, mental2);
        parent2Info.put(PARENT2_ALCOHOL, alcohol2);
        parent2Info.put(PARENT2_REASON, txtReason2.getText());
        
        parent2Info.put(PARENT2_CANCER, cancer2);
        parent2Info.put(PARENT2_DIABETES, diabetes2);
        parent2Info.put(PARENT2_HEART_DISEASE, heartdisease2);
        parent2Info.put(PARENT2_ARTHRITIS, arthritis2);
        parent2Info.put(PARENT2_ASTHAMA, asthama2);
        parent2Info.put(PARENT2_HYPERTENSION, hypertension2);
        parent2Info.put(PARENT2_ULSERS, ulcers2);
        parent2Info.put(PARENT2_TUBERCULOSIS, tuberculosis2);
        parent2Info.put(PARENT2_HYPOTENSION, hypotension2);
        request.setParent2InfoMap(parent2Info);
        JOptionPane.showMessageDialog(null, "Parent-2 Medical History saved sucessfull!!");
        
    }    
    
    public void setParent1Fields(){
        
        String chronic1 = ""; 
        String alcohol1 = ""; 
        String mental1 = "";
        String cancer1 = "";
        String diabetes1 = "";
        String heartdisease1 = "";
        String arthritis1 = "";
        String asthama1 = "";
        String hypertension1 = "";
        String ulcers1 = "";
        String tuberculosis1 = "";
        String hypotension1 = "";
        
        if(rbYes1.isSelected()) {
            chronic1 = "YES";
        }
        if(rbYes2.isSelected()){
            mental1 = "YES";
        }
        if(rbYes3.isSelected()) {
            alcohol1 = "YES";
        }
        if(rbNo1.isSelected()) {
            chronic1 = "No";
        }
        if(rbNo2.isSelected()){
            mental1 = "No";
        }
        if(rbNo3.isSelected()) {
            alcohol1 = "No";
        }
        
        
        if(cbCancer1.isSelected()) cancer1 = "CANCER\n";
        if(cbDiabetes1.isSelected()) diabetes1 = "DIABETES\n";
        if(cbHeartDisease1.isSelected()) heartdisease1 = "HEART DISEASE\n";
        if(cbArthritis1.isSelected()) arthritis1 = "ARTHRITIS\n";
        if(cbAsthama1.isSelected()) asthama1 = "ASTHAMA\n";
        if(cbHypertension1.isSelected()) hypertension1 = "HYPERTENSION\n";
        if(cbUlcers1.isSelected()) ulcers1 = "ULCERS\n";
        if(cbTuberculosis1.isSelected())tuberculosis1 = "TUBERCULOSIS\n";
        if(cbHypotension1.isSelected()) hypotension1 = "HYPOTENSION\n";
        
        
    
        Map<String, String> parent1Info = request.getParent1InfoMap();
        parent1Info.put(PARENT1_CHRONIC, chronic1);
        parent1Info.put(PARENT1_MENTAL, mental1);
        parent1Info.put(PARENT1_ALCOHOL, alcohol1);
        parent1Info.put(PARENT1_REASON, txtReason1.getText()+ " ");
        
        parent1Info.put(PARENT1_CANCER, cancer1);
        parent1Info.put(PARENT1_DIABETES, diabetes1);
        parent1Info.put(PARENT1_HEART_DISEASE, heartdisease1);
        parent1Info.put(PARENT1_ARTHRITIS, arthritis1);
        parent1Info.put(PARENT1_ASTHAMA, asthama1);
        parent1Info.put(PARENT1_HYPERTENSION, hypertension1);
        parent1Info.put(PARENT1_ULSERS, ulcers1);
        parent1Info.put(PARENT1_TUBERCULOSIS, tuberculosis1);
        parent1Info.put(PARENT1_HYPOTENSION, hypotension1);
        request.setParent1InfoMap(parent1Info);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JCheckBox cbArthritis1;
    private javax.swing.JCheckBox cbArthritis2;
    private javax.swing.JCheckBox cbAsthama1;
    private javax.swing.JCheckBox cbAsthama2;
    private javax.swing.JCheckBox cbCancer1;
    private javax.swing.JCheckBox cbCancer2;
    private javax.swing.JCheckBox cbDiabetes1;
    private javax.swing.JCheckBox cbDiabetes2;
    private javax.swing.JCheckBox cbHeartDisease1;
    private javax.swing.JCheckBox cbHeartDisease2;
    private javax.swing.JCheckBox cbHypertension1;
    private javax.swing.JCheckBox cbHypertension2;
    private javax.swing.JCheckBox cbHypotension1;
    private javax.swing.JCheckBox cbHypotension2;
    private javax.swing.JCheckBox cbTuberculosis1;
    private javax.swing.JCheckBox cbTuberculosis2;
    private javax.swing.JCheckBox cbUlcers1;
    private javax.swing.JCheckBox cbUlcers2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHypo;
    private javax.swing.JLabel lblHypo1;
    private javax.swing.JRadioButton rbNo1;
    private javax.swing.JRadioButton rbNo2;
    private javax.swing.JRadioButton rbNo3;
    private javax.swing.JRadioButton rbNo4;
    private javax.swing.JRadioButton rbNo5;
    private javax.swing.JRadioButton rbNo6;
    private javax.swing.JRadioButton rbYes1;
    private javax.swing.JRadioButton rbYes2;
    private javax.swing.JRadioButton rbYes3;
    private javax.swing.JRadioButton rbYes4;
    private javax.swing.JRadioButton rbYes5;
    private javax.swing.JRadioButton rbYes6;
    private javax.swing.JTextArea txtReason1;
    private javax.swing.JTextArea txtReason2;
    // End of variables declaration//GEN-END:variables
}
