/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterCaseworkerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FosterCaseworkerOrganization;
import Business.Organization.Organization;
import Business.Organization.PoliceOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BackgroundVerificationWorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static Business.StringConstants.ImmutableStringConstants.*;
import java.util.regex.Pattern;

/**
 *
 * @author shahd
 */
public class FosterFamilyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FosterFamilyWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private FosterCaseworkerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private BackgroundVerificationWorkRequest request;
    private Network network;
    
    public FosterFamilyWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, FosterCaseworkerOrganization organization, Enterprise enterprise, Network network,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.network = network;
        request = new BackgroundVerificationWorkRequest();
        jRadioButton1.setActionCommand("yes");
        jRadioButton2.setActionCommand("no");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPersonalInfoNext3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        personalInfoJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFNameParent1 = new javax.swing.JTextField();
        txtLNameParent1 = new javax.swing.JTextField();
        txtCitizenParent1 = new javax.swing.JTextField();
        comboParent1 = new javax.swing.JComboBox<String>();
        comboParent2 = new javax.swing.JComboBox<String>();
        txtCitizenParent2 = new javax.swing.JTextField();
        txtLNameParent2 = new javax.swing.JTextField();
        txtFNameParent2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnPersonalInfoSave = new javax.swing.JButton();
        dateParent1 = new org.jdesktop.swingx.JXDatePicker();
        dateParent2 = new org.jdesktop.swingx.JXDatePicker();
        btnPersonalInfoNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        contactInfoJPanel = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        btnContactInfoSave = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnPersonalInfoNext1 = new javax.swing.JButton();
        residentialHistoryJPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtAddress1Residential = new javax.swing.JTextField();
        txtAddress2Residential = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtCityResidential = new javax.swing.JTextField();
        txtStateResidential = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtZipCodeResidential = new javax.swing.JTextField();
        txtCountryResidential = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnSaveResidential = new javax.swing.JButton();
        dateresidential = new org.jdesktop.swingx.JXDatePicker();
        btnPersonalInfoNext2 = new javax.swing.JButton();
        employmentHistoryJPanel = new javax.swing.JPanel();
        txtCurrentEmployer = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtJobTitleCurrent = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtPreviousEmployer = new javax.swing.JTextField();
        txtJobTitlePrevious = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnEmployerHistSave = new javax.swing.JButton();
        dateEmploymentCurrent = new org.jdesktop.swingx.JXDatePicker();
        dateEmploymentPrevious = new org.jdesktop.swingx.JXDatePicker();
        btnPersonalInfoNext4 = new javax.swing.JButton();
        referencesJPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtnamereference = new javax.swing.JTextField();
        txtRelationshipReference = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtAddressReference = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtCityReference = new javax.swing.JTextField();
        btnDataSubmit = new javax.swing.JButton();
        txtTelephoneReference = new javax.swing.JTextField();
        txtStateReference = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtZipReference = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtCountryReference = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        btnPersonalInfoNext3.setBackground(new java.awt.Color(0, 0, 0));
        btnPersonalInfoNext3.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalInfoNext3.setText("Next");
        btnPersonalInfoNext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoNext3ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(0, 102, 102));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));

        personalInfoJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Parent 1 Information");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Citizenship");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Birth Date");

        txtFNameParent1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtLNameParent1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtCitizenParent1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        comboParent1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        comboParent1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        comboParent2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        comboParent2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        txtCitizenParent2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtLNameParent2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtFNameParent2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("First Name");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Last Name");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Citizenship");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Gender");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Birth Date");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Parent 2 Information");

        btnPersonalInfoSave.setBackground(new java.awt.Color(0, 0, 0));
        btnPersonalInfoSave.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnPersonalInfoSave.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalInfoSave.setText("Save");
        btnPersonalInfoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoSaveActionPerformed(evt);
            }
        });

        btnPersonalInfoNext.setBackground(new java.awt.Color(0, 0, 0));
        btnPersonalInfoNext.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnPersonalInfoNext.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalInfoNext.setText("Next>>");
        btnPersonalInfoNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoNextActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personalInfoJPanelLayout = new javax.swing.GroupLayout(personalInfoJPanel);
        personalInfoJPanel.setLayout(personalInfoJPanelLayout);
        personalInfoJPanelLayout.setHorizontalGroup(
            personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                            .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(69, 69, 69)
                            .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCitizenParent1)
                                .addComponent(txtLNameParent1)
                                .addComponent(txtFNameParent1)
                                .addComponent(comboParent1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateParent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel12)
                        .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                            .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(69, 69, 69)
                            .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCitizenParent2)
                                .addComponent(txtLNameParent2)
                                .addComponent(txtFNameParent2)
                                .addComponent(dateParent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboParent2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPersonalInfoSave, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPersonalInfoNext)))
                .addContainerGap(420, Short.MAX_VALUE))
        );

        personalInfoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPersonalInfoNext, btnPersonalInfoSave});

        personalInfoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        personalInfoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel7, jLabel8, jLabel9});

        personalInfoJPanelLayout.setVerticalGroup(
            personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFNameParent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLNameParent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCitizenParent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboParent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateParent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFNameParent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLNameParent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCitizenParent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboParent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateParent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPersonalInfoSave)
                    .addComponent(btnPersonalInfoNext)
                    .addComponent(btnBack))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personal Information", personalInfoJPanel);

        contactInfoJPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtEmail.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtPhone.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtAddress1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtAddress2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtCity.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtState.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtZipCode.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtCountry.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        btnContactInfoSave.setBackground(new java.awt.Color(0, 0, 0));
        btnContactInfoSave.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnContactInfoSave.setForeground(new java.awt.Color(255, 255, 255));
        btnContactInfoSave.setText("Save");
        btnContactInfoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactInfoSaveActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Country");

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Zip Code");

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("State");

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("City");

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Address Line 2");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Address Line 1");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Phone Number");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Email ID");

        btnPersonalInfoNext1.setBackground(new java.awt.Color(0, 0, 0));
        btnPersonalInfoNext1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnPersonalInfoNext1.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalInfoNext1.setText("Next>>");
        btnPersonalInfoNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoNext1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contactInfoJPanelLayout = new javax.swing.GroupLayout(contactInfoJPanel);
        contactInfoJPanel.setLayout(contactInfoJPanelLayout);
        contactInfoJPanelLayout.setHorizontalGroup(
            contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactInfoJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContactInfoSave, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21)
                    .addComponent(jLabel13)
                    .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contactInfoJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(107, 107, 107)
                            .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(txtAddress2)
                                .addComponent(txtAddress1)))
                        .addGroup(contactInfoJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(contactInfoJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPersonalInfoNext1)))
                .addContainerGap(385, Short.MAX_VALUE))
        );

        contactInfoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel20, jLabel21, jLabel22, jLabel23, jLabel24, jLabel29});

        contactInfoJPanelLayout.setVerticalGroup(
            contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactInfoJPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contactInfoJPanelLayout.createSequentialGroup()
                        .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20))
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCountry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContactInfoSave)
                    .addComponent(btnPersonalInfoNext1))
                .addGap(152, 152, 152))
        );

        contactInfoJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel20, jLabel21, jLabel22, jLabel23, jLabel24, jLabel29, txtAddress1, txtAddress2, txtCity, txtCountry, txtEmail, txtPhone, txtState, txtZipCode});

        jTabbedPane1.addTab("Contact Information", contactInfoJPanel);

        residentialHistoryJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel19.setText("Previous Address:");

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Address Line 1");

        txtAddress1Residential.setEnabled(false);

        txtAddress2Residential.setEnabled(false);

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Address Line 2");

        jLabel37.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("City");

        txtCityResidential.setEnabled(false);

        txtStateResidential.setEnabled(false);

        jLabel38.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("State");

        jLabel39.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Zip Code");

        txtZipCodeResidential.setEnabled(false);

        txtCountryResidential.setEnabled(false);
        txtCountryResidential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryResidentialActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setText("Country");

        jLabel41.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 102, 102));
        jLabel41.setText("Date Moved to this Address");

        jLabel42.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel42.setText("Have you been at the present address for the last five years");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        btnSaveResidential.setBackground(new java.awt.Color(0, 0, 0));
        btnSaveResidential.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnSaveResidential.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveResidential.setText("Save");
        btnSaveResidential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveResidentialActionPerformed(evt);
            }
        });

        dateresidential.setEnabled(false);

        btnPersonalInfoNext2.setBackground(new java.awt.Color(0, 0, 0));
        btnPersonalInfoNext2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnPersonalInfoNext2.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalInfoNext2.setText("Next>>");
        btnPersonalInfoNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoNext2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout residentialHistoryJPanelLayout = new javax.swing.GroupLayout(residentialHistoryJPanel);
        residentialHistoryJPanel.setLayout(residentialHistoryJPanelLayout);
        residentialHistoryJPanelLayout.setHorizontalGroup(
            residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(59, 59, 59)
                        .addComponent(jRadioButton1)
                        .addGap(46, 46, 46)
                        .addComponent(jRadioButton2))
                    .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                            .addComponent(btnSaveResidential, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(199, 199, 199)
                            .addComponent(btnPersonalInfoNext2))
                        .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, residentialHistoryJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateresidential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, residentialHistoryJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCountryResidential, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, residentialHistoryJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtZipCodeResidential, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, residentialHistoryJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtStateResidential, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, residentialHistoryJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCityResidential, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, residentialHistoryJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAddress2Residential, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, residentialHistoryJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAddress1Residential, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        residentialHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel35, jLabel36, jLabel37, jLabel38, jLabel39, jLabel40, jLabel41});

        residentialHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateresidential, txtAddress1Residential, txtAddress2Residential, txtCityResidential, txtCountryResidential, txtStateResidential, txtZipCodeResidential});

        residentialHistoryJPanelLayout.setVerticalGroup(
            residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(16, 16, 16)
                .addComponent(jLabel19)
                .addGap(24, 24, 24)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAddress1Residential, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAddress2Residential, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCityResidential, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStateResidential, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipCodeResidential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtCountryResidential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(dateresidential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveResidential)
                    .addComponent(btnPersonalInfoNext2))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        residentialHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel35, jLabel36, txtAddress1Residential});

        residentialHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel37, txtCityResidential});

        residentialHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel38, txtStateResidential});

        residentialHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel39, txtZipCodeResidential});

        residentialHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel40, txtCountryResidential});

        residentialHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateresidential, jLabel41});

        jTabbedPane1.addTab("Residential History", residentialHistoryJPanel);

        employmentHistoryJPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtCurrentEmployer.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtCurrentEmployer.setForeground(new java.awt.Color(102, 102, 102));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Current Employer");

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Job Title");

        txtJobTitleCurrent.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtJobTitleCurrent.setForeground(new java.awt.Color(102, 102, 102));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Date of Employment");

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Previous Employer");

        txtPreviousEmployer.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtPreviousEmployer.setForeground(new java.awt.Color(102, 102, 102));

        txtJobTitlePrevious.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtJobTitlePrevious.setForeground(new java.awt.Color(102, 102, 102));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Job Title");

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Date of Employment");

        btnEmployerHistSave.setBackground(new java.awt.Color(0, 0, 0));
        btnEmployerHistSave.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnEmployerHistSave.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployerHistSave.setText("Save");
        btnEmployerHistSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployerHistSaveActionPerformed(evt);
            }
        });

        btnPersonalInfoNext4.setBackground(new java.awt.Color(0, 0, 0));
        btnPersonalInfoNext4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnPersonalInfoNext4.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalInfoNext4.setText("Next>>");
        btnPersonalInfoNext4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoNext4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout employmentHistoryJPanelLayout = new javax.swing.GroupLayout(employmentHistoryJPanel);
        employmentHistoryJPanel.setLayout(employmentHistoryJPanelLayout);
        employmentHistoryJPanelLayout.setHorizontalGroup(
            employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employmentHistoryJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employmentHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtJobTitlePrevious))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employmentHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateEmploymentPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employmentHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPreviousEmployer))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employmentHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateEmploymentCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employmentHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtJobTitleCurrent))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employmentHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCurrentEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(employmentHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(btnEmployerHistSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPersonalInfoNext4)))
                .addContainerGap(398, Short.MAX_VALUE))
        );

        employmentHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel16, jLabel25, jLabel26, jLabel27, jLabel28});

        employmentHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEmployerHistSave, btnPersonalInfoNext4});

        employmentHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateEmploymentCurrent, dateEmploymentPrevious, txtCurrentEmployer, txtJobTitleCurrent, txtJobTitlePrevious, txtPreviousEmployer});

        employmentHistoryJPanelLayout.setVerticalGroup(
            employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employmentHistoryJPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCurrentEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtJobTitleCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateEmploymentCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtPreviousEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJobTitlePrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(dateEmploymentPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmployerHistSave)
                    .addComponent(btnPersonalInfoNext4))
                .addGap(27, 27, 27))
        );

        employmentHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateEmploymentCurrent, dateEmploymentPrevious, jLabel15, jLabel16, jLabel25, jLabel26, jLabel27, jLabel28, txtCurrentEmployer, txtJobTitleCurrent, txtJobTitlePrevious, txtPreviousEmployer});

        jTabbedPane1.addTab("Employment History", employmentHistoryJPanel);

        referencesJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Name");

        txtnamereference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtRelationshipReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Relationship");

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Telephone Number");

        txtAddressReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Address");

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("City");

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("State");

        txtCityReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        btnDataSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnDataSubmit.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnDataSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnDataSubmit.setText("Submit");
        btnDataSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataSubmitActionPerformed(evt);
            }
        });

        txtTelephoneReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        txtStateReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtStateReference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateReferenceActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Zip Code");

        txtZipReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel43.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 102, 102));
        jLabel43.setText("Country");

        txtCountryReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        javax.swing.GroupLayout referencesJPanelLayout = new javax.swing.GroupLayout(referencesJPanel);
        referencesJPanel.setLayout(referencesJPanelLayout);
        referencesJPanelLayout.setHorizontalGroup(
            referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referencesJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referencesJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel43)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCountryReference, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referencesJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtZipReference, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referencesJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStateReference, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referencesJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCityReference, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referencesJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAddressReference))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referencesJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelephoneReference, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referencesJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRelationshipReference, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referencesJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnamereference, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                    .addComponent(btnDataSubmit))
                .addContainerGap(453, Short.MAX_VALUE))
        );

        referencesJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAddressReference, txtCityReference, txtCountryReference, txtRelationshipReference, txtStateReference, txtTelephoneReference, txtZipReference, txtnamereference});

        referencesJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel17, jLabel18, jLabel30, jLabel31, jLabel32, jLabel33, jLabel34, jLabel43});

        referencesJPanelLayout.setVerticalGroup(
            referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referencesJPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtnamereference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtRelationshipReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtTelephoneReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtAddressReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtStateReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtZipReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtCountryReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDataSubmit)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        referencesJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel17, jLabel18, jLabel30, jLabel31, jLabel32, jLabel33, jLabel34, jLabel43, txtAddressReference, txtCityReference, txtCountryReference, txtRelationshipReference, txtStateReference, txtTelephoneReference, txtZipReference, txtnamereference});

        jTabbedPane1.addTab("References", referencesJPanel);

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Enter Foster Family Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jSeparator1)
            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonalInfoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoSaveActionPerformed
        // TODO add your handling code here:
        
        Map<String, String> personalInfo;
        String p1fname = txtFNameParent1.getText();
        String p1lname = txtLNameParent1.getText();
        String p1citizenship = txtCitizenParent1.getText();
        String p1gender = comboParent1.getSelectedItem().toString();
        if(dateParent1.getDate()==null || dateParent2.getDate() == null){
           JOptionPane.showMessageDialog(null, "Please select date values");
            return; 
        }
        Date date = dateParent1.getDate();
        DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String p1birth = oDateFormat.format(date);
        String p2fname = txtFNameParent2.getText();
        String p2lname = txtLNameParent2.getText();
        String p2citizenship = txtCitizenParent2.getText();
        String p2gender = comboParent2.getSelectedItem().toString();
        Date date1 = dateParent2.getDate();
        String p2birth = oDateFormat.format(date1);
        if(p1fname.equals("") || p1lname.equals("") || p1citizenship.equals("") ||
            p2fname.equals("") || p2lname.equals("") || p2citizenship.equals("")   ){
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
            return;
        }
        
        request.setMessage("temp message");
        personalInfo = request.getPersonalInfoMap();
        personalInfo.put(PARENT1_FIRST_NAME, p1fname);
        personalInfo.put(PARENT2_FIRST_NAME, p2fname);
        personalInfo.put(PARENT1_LAST_NAME, p1lname);
        personalInfo.put(PARENT2_LAST_NAME, p2lname);
        personalInfo.put(PARENT1_CITIZENSHIP, p1citizenship);
        personalInfo.put(PARENT2_CITIZENSHIP, p2citizenship);
        personalInfo.put(PARENT1_GENDER, p1gender);
        personalInfo.put(PARENT2_GENDER, p2gender);
        personalInfo.put(PARENT1_BIRTH, p1birth);
        personalInfo.put(PARENT2_BIRTH, p2birth);
        personalInfo.put("personalInfoStatus", "false");
        request.setPersonalInfoMap(personalInfo);
        JOptionPane.showMessageDialog(null, "Personal Info Saved Successfully!");
        
        //disable
        btnPersonalInfoSave.setEnabled(false);
        txtFNameParent1.setEnabled(false);
        txtLNameParent1.setEnabled(false);
        txtCitizenParent1.setEnabled(false);
        comboParent1.setEnabled(false);
        dateParent1.setEnabled(false);
        txtFNameParent2.setEnabled(false);
        txtLNameParent2.setEnabled(false);
        txtCitizenParent2.setEnabled(false);
        comboParent2.setEnabled(false);
        dateParent2.setEnabled(false);
    }//GEN-LAST:event_btnPersonalInfoSaveActionPerformed
        
    private void btnPersonalInfoNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoNextActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_btnPersonalInfoNextActionPerformed

    private void btnPersonalInfoNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoNext1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnPersonalInfoNext1ActionPerformed

    private void btnPersonalInfoNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoNext2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnPersonalInfoNext2ActionPerformed

    private void btnPersonalInfoNext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoNext3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPersonalInfoNext3ActionPerformed

    private void btnPersonalInfoNext4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoNext4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnPersonalInfoNext4ActionPerformed

    private void btnContactInfoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactInfoSaveActionPerformed
        // TODO add your handling code here:
        Map<String, String> contactInfoMap;
        String email = txtEmail.getText();
        
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
							"[a-zA-Z0-9_+&*-]+)*@" + 
							"(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
							"A-Z]{2,7}$"; 
	Pattern pat = Pattern.compile(emailRegex);
        
        
        if(pat.matcher(email).matches()!= true){
            JOptionPane.showMessageDialog(null, "Expecting a valiad Email!");
            return;
        }
        
        
        String phone = txtPhone.getText();
        String address1 = txtAddress1.getText();
        String address2 = txtAddress2.getText();
        String city = txtCity.getText();
        String state = txtState.getText();
        String zipcode = txtZipCode.getText();
        String country = txtCountry.getText();
        if(email.equals("") || phone.equals("") || address1.equals("") ||
            address2.equals("") || city.equals("") || state.equals("") || zipcode.equals("") || country.equals("")  ){
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
            return;
        }
        
        try{
            Integer.parseInt(txtZipCode.getText());
            Integer.parseInt(txtPhone.getText());
            
        }catch(NumberFormatException e){
            
            JOptionPane.showMessageDialog(null, "Expecting a valid number!");
            return;
        }
        
        contactInfoMap = request.getContactInfoMap();
        contactInfoMap.put(PARENT_EMAIL, email);
        contactInfoMap.put(PARENT_PHONE, phone);
        contactInfoMap.put(PARENT_ADDRESS1, address1);
        contactInfoMap.put(PARENT_ADDRESS2, address2);
        contactInfoMap.put(PARENT_CITY, city);
        contactInfoMap.put(PARENT_STATE, state);
        contactInfoMap.put(PARENT_ZIPCODE, zipcode);
        contactInfoMap.put(PARENT_COUNTRY, country);
        contactInfoMap.put("contactInfoStatus", "false");
        request.setContactInfoMap(contactInfoMap);
        
        JOptionPane.showMessageDialog(null, "Contact Info Saved Successfully!");
        
        //disable
        btnContactInfoSave.setEnabled(false);
        txtPhone.setEnabled(false);
        txtAddress1.setEnabled(false);
        txtAddress2.setEnabled(false);
        txtCity.setEnabled(false);
        txtState.setEnabled(false);
        txtZipCode.setEnabled(false);
        txtCountry.setEnabled(false);
        txtEmail.setEnabled(false);
        
    }//GEN-LAST:event_btnContactInfoSaveActionPerformed

    private void btnSaveResidentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveResidentialActionPerformed
        // TODO add your handling code here:
        Map<String, String> residentialInfoMap;
//        System.out.println("buttonGroup1.getSelection().getActionCommand()"+buttonGroup1.getSelection().getActionCommand());
//        if(buttonGroup1.getSelection().getActionCommand().equals(null)){
//            JOptionPane.showMessageDialog(null, "Please select yes or no!");
//            return;
//        }
        String moved = buttonGroup1.getSelection().getActionCommand();
        residentialInfoMap = request.getResidentialHistoryMap();
        if(moved.equals("no")){
            String address1 = txtAddress1.getText();
            String address2 = txtAddress2.getText();
            String city = txtCity.getText();
            String state = txtState.getText();
            String zipcode = txtZipCode.getText();
            String country = txtCountry.getText();
            if(dateresidential.getDate() == null){
                JOptionPane.showMessageDialog(null, "Please select the moving date");
                return;
            }
            Date date1 = dateresidential.getDate();
            if(address1.equals("") || address2.equals("") ||  city.equals("") || state.equals("") || zipcode.equals("") || country.equals("")  ){
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
            return;
            }
            DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String datemoved = oDateFormat.format(date1);
        
        try{
            Integer.parseInt(txtZipCode.getText());
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Expecting a zip code!");
            return;
        }
        
            System.out.println("moved check"+moved);
        residentialInfoMap.put("movedcheck", moved);
        residentialInfoMap.put(PARENT_OLD_ADDRESS1, address1);
        residentialInfoMap.put(PARENT_OLD_ADDRESS2, address2);
        residentialInfoMap.put(PARENT_OLD_CITY, city);
        residentialInfoMap.put(PARENT_OLD_STATE, state);
        residentialInfoMap.put(PARENT_OLD_ZIPCODE, zipcode);
        residentialInfoMap.put(PARENT_OLD_COUNTRY, country);
        residentialInfoMap.put(ADDRESS_MOVED_ON, datemoved);
        residentialInfoMap.put("residentialInfoStatus", "false");
        request.setResidentialHistoryMap(residentialInfoMap);
        }
        else{
            residentialInfoMap.put("movedcheck", moved);
            residentialInfoMap.put("residentialInfoStatus", "false");
            request.setResidentialHistoryMap(residentialInfoMap);
        }
        
        JOptionPane.showMessageDialog(null, "Residential History Saved Successfully!");
        btnSaveResidential.setEnabled(false);
        
    }//GEN-LAST:event_btnSaveResidentialActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        txtAddress1Residential.setEnabled(false);
        txtAddress2Residential.setEnabled(false);
        txtCityResidential.setEnabled(false);
        txtStateResidential.setEnabled(false);
        txtZipCodeResidential.setEnabled(false);
        txtCountryResidential.setEnabled(false);
        dateresidential.setEnabled(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        txtAddress1Residential.setEnabled(true);
        txtAddress2Residential.setEnabled(true);
        txtCityResidential.setEnabled(true);
        txtStateResidential.setEnabled(true);
        txtZipCodeResidential.setEnabled(true);
        txtCountryResidential.setEnabled(true);
        dateresidential.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btnEmployerHistSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployerHistSaveActionPerformed
        // TODO add your handling code here:
        Map<String, String> employmentMap;
        String currentEmp = txtCurrentEmployer.getText();
        String jobTitleCurrent = txtJobTitleCurrent.getText();
        if(dateEmploymentCurrent.getDate() == null || dateEmploymentPrevious.getDate()== null){
                JOptionPane.showMessageDialog(null, "Please select the dates!");
                return;
        }
        Date date1 = dateEmploymentCurrent.getDate();
        DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateofEmpCurrent = oDateFormat.format(date1);
        String previousEmp = txtPreviousEmployer.getText();
        String jobTitlePrevious = txtJobTitlePrevious.getText();
        String country = txtCountry.getText();
        Date date2 = dateEmploymentPrevious.getDate();
        String dateofEmpPrevious = oDateFormat.format(date2);
        if(currentEmp.equals("") || jobTitleCurrent.equals("") ||  previousEmp.equals("") || jobTitlePrevious.equals("") ){
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
            return;
            }
        
        employmentMap = request.getEmploymentHistoryMap();
        employmentMap.put(PARENT_CURRENT_EMPLOYER, currentEmp);
        employmentMap.put(PARENT_JOB_TITLE, jobTitleCurrent);
        employmentMap.put(DATE_OF_CURRENT_JOB, dateofEmpCurrent);
        employmentMap.put(PARENT_PREVIOUS_EMPLOYER, previousEmp);
        employmentMap.put(PARENT_PREVIOUS_JOB_TITLE, jobTitlePrevious);
        employmentMap.put(DATE_OF_PREVIOUS_JOB, dateofEmpPrevious);
        employmentMap.put("employmentInfoStatus", "false");
        request.setEmploymentHistoryMap(employmentMap);
        
        JOptionPane.showMessageDialog(null, "Employement History Saved Successfully!");
        
        //disable
        btnEmployerHistSave.setEnabled(false);
        txtCurrentEmployer.setEnabled(false);
        txtJobTitleCurrent.setEnabled(false);
        dateEmploymentCurrent.setEnabled(false);
        txtPreviousEmployer.setEnabled(false);
        txtJobTitlePrevious.setEnabled(false);
        dateEmploymentPrevious.setEnabled(false);
        
    }//GEN-LAST:event_btnEmployerHistSaveActionPerformed

    private void btnDataSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSubmitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Do you want to proceed?", "WARNING",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        Map<String, String> referenceMap;
        String nameReference = txtnamereference.getText();
        String relationReference = txtRelationshipReference.getText();
        String telephoneReference = txtTelephoneReference.getText();
        String addressReference = txtAddressReference.getText();
        String cityReference = txtCityReference.getText();
        String stateReference = txtStateReference.getText();
        String zipcodeReference = txtZipReference.getText();
        String countryReference = txtCountryReference.getText();
        if(nameReference.equals("") || relationReference.equals("") || telephoneReference.equals("") ||
            addressReference.equals("") || cityReference.equals("") || stateReference.equals("") || zipcodeReference.equals("") || countryReference.equals("")  ){
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
            return;
        }
        try{
            Integer.parseInt(zipcodeReference);
            Integer.parseInt(telephoneReference);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Expecting a valid Number!");
            return;
        }
        referenceMap = request.getReferenceMap();
        referenceMap.put(REFERENCE_NAME, nameReference);
        referenceMap.put(REFERENCE_RELATION, relationReference);
        referenceMap.put(REFERENCE_PHONE, telephoneReference);
        referenceMap.put(REFERENCE_ADDRESS, addressReference);
        referenceMap.put(REFERENCE_CITY, cityReference);
        referenceMap.put(REFERENCE_STATE, stateReference);
        referenceMap.put(REFERENCE_ZIPCODE, zipcodeReference);
        referenceMap.put(REFERENCE_COUNTRY, countryReference);
        referenceMap.put("referenceInfoStatus", "false");
        request.setReferenceMap(referenceMap);
        request.setSender(userAccount);
        request.setStatus("Sent");
        Organization org = null;
        for(Network net : business.getNetworkList()){
            if(net.equals(network)){
            for(Enterprise enterprise : net.getEnterpriseDirectory().getEnterpriseList()){
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if (organization instanceof PoliceOrganization){
                        org = organization;
                        break;
                    }
                }
            }
        }
        }
        request.setOrgName(org.toString());
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        System.out.println("Network is: "+network);
        JOptionPane.showMessageDialog(null, "Police Verification Request Created Successfully!!");
        
        FosterCaseWorkerManageFamilyJPanel fosterCaseWorkerManageFamilyJPanel = new FosterCaseWorkerManageFamilyJPanel(userProcessContainer, userAccount,  organization,  enterprise,network, business);
        userProcessContainer.add("FosterCaseWorkerManageFamilyJPanel", fosterCaseWorkerManageFamilyJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        } else{
            //do nothing;
        }
    }//GEN-LAST:event_btnDataSubmitActionPerformed

    private void txtCountryResidentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryResidentialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryResidentialActionPerformed

    private void txtStateReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateReferenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateReferenceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContactInfoSave;
    private javax.swing.JButton btnDataSubmit;
    private javax.swing.JButton btnEmployerHistSave;
    private javax.swing.JButton btnPersonalInfoNext;
    private javax.swing.JButton btnPersonalInfoNext1;
    private javax.swing.JButton btnPersonalInfoNext2;
    private javax.swing.JButton btnPersonalInfoNext3;
    private javax.swing.JButton btnPersonalInfoNext4;
    private javax.swing.JButton btnPersonalInfoSave;
    private javax.swing.JButton btnSaveResidential;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboParent1;
    private javax.swing.JComboBox<String> comboParent2;
    private javax.swing.JPanel contactInfoJPanel;
    private org.jdesktop.swingx.JXDatePicker dateEmploymentCurrent;
    private org.jdesktop.swingx.JXDatePicker dateEmploymentPrevious;
    private org.jdesktop.swingx.JXDatePicker dateParent1;
    private org.jdesktop.swingx.JXDatePicker dateParent2;
    private org.jdesktop.swingx.JXDatePicker dateresidential;
    private javax.swing.JPanel employmentHistoryJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel personalInfoJPanel;
    private javax.swing.JPanel referencesJPanel;
    private javax.swing.JPanel residentialHistoryJPanel;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress1Residential;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtAddress2Residential;
    private javax.swing.JTextField txtAddressReference;
    private javax.swing.JTextField txtCitizenParent1;
    private javax.swing.JTextField txtCitizenParent2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCityReference;
    private javax.swing.JTextField txtCityResidential;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtCountryReference;
    private javax.swing.JTextField txtCountryResidential;
    private javax.swing.JTextField txtCurrentEmployer;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFNameParent1;
    private javax.swing.JTextField txtFNameParent2;
    private javax.swing.JTextField txtJobTitleCurrent;
    private javax.swing.JTextField txtJobTitlePrevious;
    private javax.swing.JTextField txtLNameParent1;
    private javax.swing.JTextField txtLNameParent2;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPreviousEmployer;
    private javax.swing.JTextField txtRelationshipReference;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStateReference;
    private javax.swing.JTextField txtStateResidential;
    private javax.swing.JTextField txtTelephoneReference;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JTextField txtZipCodeResidential;
    private javax.swing.JTextField txtZipReference;
    private javax.swing.JTextField txtnamereference;
    // End of variables declaration//GEN-END:variables
}
