/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PoliceRole;

import Business.Enterprise.Enterprise;
import Business.Organization.PoliceOrganization;
import static Business.StringConstants.ImmutableStringConstants.*;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BackgroundVerificationWorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Shubham
 */
public class PoliceViewDataJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PoliceViewDataJPanel
     */
    private JPanel userProcessContainer;
    private BackgroundVerificationWorkRequest request;
    private UserAccount account;
    private PoliceOrganization organization;
    private Enterprise enterprise;

    PoliceViewDataJPanel(JPanel userProcessContainer, BackgroundVerificationWorkRequest request, UserAccount account, PoliceOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        setFields();
        if(this.request.getStatus().equals("Completed")){
            btnDataSubmit.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        personalInfoJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFNameParent1 = new javax.swing.JTextField();
        txtLNameParent1 = new javax.swing.JTextField();
        txtCitizenParent1 = new javax.swing.JTextField();
        txtParent1Gender = new javax.swing.JTextField();
        txtLNameParent2 = new javax.swing.JTextField();
        txtFNameParent2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnPersonalInfoNext = new javax.swing.JButton();
        txtParent1BirthDate = new javax.swing.JTextField();
        txtParent2BirthDate = new javax.swing.JTextField();
        txtCitizenParent3 = new javax.swing.JTextField();
        txtParent2Gender = new javax.swing.JTextField();
        contactInfoJPanel = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnPersonalInfoNext1 = new javax.swing.JButton();
        residentialHistoryJPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtAddress1Residential = new javax.swing.JTextField();
        txtAddress2Residential = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtCityResidential = new javax.swing.JTextField();
        txtStateResidential = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtZipCodeResidential = new javax.swing.JTextField();
        txtCountryResidential = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btnPersonalInfoNext2 = new javax.swing.JButton();
        txtmoved = new javax.swing.JTextField();
        txtDateMoved = new javax.swing.JTextField();
        employmentHistoryJPanel = new javax.swing.JPanel();
        txtCurrentEmployer = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtJobTitleCurrent = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtPreviousEmployer = new javax.swing.JTextField();
        txtJobTitlePrevious = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnPersonalInfoNext4 = new javax.swing.JButton();
        txtdatecurrent = new javax.swing.JTextField();
        txtdateprevious = new javax.swing.JTextField();
        referencesJPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtnamereference = new javax.swing.JTextField();
        txtRelationshipReference = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtAddressReference = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtCityReference = new javax.swing.JTextField();
        btnDataSubmit = new javax.swing.JButton();
        txtTelephoneReference = new javax.swing.JTextField();
        txtStateReference = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtZipReference = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtCountryReference = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));

        personalInfoJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setText("Parent 1 Information");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("First Name");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Last Name");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Citizenship");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Gender");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Birth Date");

        txtFNameParent1.setEnabled(false);

        txtLNameParent1.setEnabled(false);

        txtCitizenParent1.setEnabled(false);

        txtParent1Gender.setEnabled(false);

        txtLNameParent2.setEnabled(false);

        txtFNameParent2.setEnabled(false);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("First Name");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Last Name");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Citizenship");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Gender");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Birth Date");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel12.setText("Parent 2 Information");

        btnPersonalInfoNext.setBackground(new java.awt.Color(0, 0, 0));
        btnPersonalInfoNext.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnPersonalInfoNext.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalInfoNext.setText("Next>>");
        btnPersonalInfoNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoNextActionPerformed(evt);
            }
        });

        txtParent1BirthDate.setEnabled(false);

        txtParent2BirthDate.setEnabled(false);

        txtCitizenParent3.setEnabled(false);

        txtParent2Gender.setEnabled(false);

        javax.swing.GroupLayout personalInfoJPanelLayout = new javax.swing.GroupLayout(personalInfoJPanel);
        personalInfoJPanel.setLayout(personalInfoJPanelLayout);
        personalInfoJPanelLayout.setHorizontalGroup(
            personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCitizenParent1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCitizenParent3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtParent2BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLNameParent2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLNameParent1))
                            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtParent1Gender))
                            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtParent2Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtParent1BirthDate))
                            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFNameParent1)
                                    .addComponent(txtFNameParent2))))
                        .addComponent(btnPersonalInfoNext, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel12)))
                .addContainerGap(674, Short.MAX_VALUE))
        );

        personalInfoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        personalInfoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCitizenParent3, txtFNameParent1, txtFNameParent2, txtLNameParent1, txtLNameParent2, txtParent1BirthDate, txtParent1Gender, txtParent2BirthDate, txtParent2Gender});

        personalInfoJPanelLayout.setVerticalGroup(
            personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFNameParent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLNameParent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCitizenParent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParent1Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParent1BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                        .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFNameParent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personalInfoJPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLNameParent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCitizenParent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParent2Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParent2BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPersonalInfoNext)
                .addContainerGap(513, Short.MAX_VALUE))
        );

        personalInfoJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, txtCitizenParent3, txtFNameParent1, txtFNameParent2, txtLNameParent1, txtLNameParent2, txtParent1BirthDate, txtParent1Gender, txtParent2BirthDate, txtParent2Gender});

        jTabbedPane1.addTab("Personal Information", personalInfoJPanel);

        contactInfoJPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtEmail.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtEmail.setEnabled(false);

        txtPhone.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtPhone.setEnabled(false);

        txtAddress1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtAddress1.setEnabled(false);

        txtAddress2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtAddress2.setEnabled(false);

        txtCity.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtCity.setEnabled(false);

        txtState.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtState.setEnabled(false);

        txtZipCode.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtZipCode.setEnabled(false);

        txtCountry.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtCountry.setEnabled(false);

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel24.setText("Country");

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel29.setText("Zip Code");

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel23.setText("State");

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel22.setText("City");

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel21.setText("Address Line 2");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel20.setText("Address Line 1");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel14.setText("Phone Number");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel13.setText("Email ID");

        btnPersonalInfoNext1.setBackground(new java.awt.Color(0, 0, 0));
        btnPersonalInfoNext1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnPersonalInfoNext1.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalInfoNext1.setText("Next>>");
        btnPersonalInfoNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoNext1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contactInfoJPanelLayout = new javax.swing.GroupLayout(contactInfoJPanel);
        contactInfoJPanel.setLayout(contactInfoJPanelLayout);
        contactInfoJPanelLayout.setHorizontalGroup(
            contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactInfoJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel29)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21)
                    .addComponent(jLabel13)
                    .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contactInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(107, 107, 107)
                                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(txtAddress2)
                                    .addComponent(txtAddress1)))
                            .addGroup(contactInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPersonalInfoNext1)))
                .addContainerGap(617, Short.MAX_VALUE))
        );

        contactInfoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel20, jLabel21, jLabel22, jLabel23, jLabel24, jLabel29});

        contactInfoJPanelLayout.setVerticalGroup(
            contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactInfoJPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contactInfoJPanelLayout.createSequentialGroup()
                        .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20))
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addGroup(contactInfoJPanelLayout.createSequentialGroup()
                        .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contactInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnPersonalInfoNext1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contact Information", contactInfoJPanel);

        residentialHistoryJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel19.setText("Previous Address");

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Address Line 1");

        txtAddress1Residential.setEnabled(false);

        txtAddress2Residential.setEnabled(false);

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Address Line 2");

        jLabel37.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("City");

        txtCityResidential.setEnabled(false);

        txtStateResidential.setEnabled(false);

        jLabel38.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("State");

        jLabel39.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Zip Code");

        txtZipCodeResidential.setEnabled(false);

        txtCountryResidential.setEnabled(false);

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setText("Country");

        jLabel41.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 102, 102));
        jLabel41.setText("Date Moved to this Address");

        jLabel42.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel42.setText("Have you been at the present address for the last five years");

        btnPersonalInfoNext2.setBackground(new java.awt.Color(0, 0, 0));
        btnPersonalInfoNext2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnPersonalInfoNext2.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalInfoNext2.setText("Next>>");
        btnPersonalInfoNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoNext2ActionPerformed(evt);
            }
        });

        txtmoved.setEnabled(false);

        txtDateMoved.setEnabled(false);

        javax.swing.GroupLayout residentialHistoryJPanelLayout = new javax.swing.GroupLayout(residentialHistoryJPanel);
        residentialHistoryJPanel.setLayout(residentialHistoryJPanelLayout);
        residentialHistoryJPanelLayout.setHorizontalGroup(
            residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPersonalInfoNext2)
                    .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtCountryResidential, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, residentialHistoryJPanelLayout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel41)
                                    .addGap(36, 36, 36)
                                    .addComponent(txtDateMoved, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel40)
                                .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtmoved, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel35)
                                    .addGap(36, 36, 36)
                                    .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAddress1Residential)
                                        .addComponent(txtAddress2Residential)
                                        .addComponent(txtCityResidential)
                                        .addComponent(txtStateResidential)
                                        .addComponent(txtZipCodeResidential)))
                                .addComponent(jLabel19)
                                .addComponent(jLabel36)
                                .addComponent(jLabel37)
                                .addComponent(jLabel39)
                                .addComponent(jLabel38)))))
                .addContainerGap(388, Short.MAX_VALUE))
        );

        residentialHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel35, jLabel36, jLabel37, jLabel38, jLabel39, jLabel40, jLabel41});

        residentialHistoryJPanelLayout.setVerticalGroup(
            residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmoved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel19)
                .addGap(23, 23, 23)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtAddress1Residential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtAddress2Residential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtCityResidential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(txtStateResidential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(txtZipCodeResidential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(residentialHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(41, 41, 41)))
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtCountryResidential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(residentialHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel41)
                    .addComponent(txtDateMoved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPersonalInfoNext2)
                .addContainerGap())
        );

        residentialHistoryJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel35, jLabel36, jLabel37, jLabel39, jLabel40, jLabel41, txtAddress1Residential, txtAddress2Residential, txtCityResidential, txtCountryResidential, txtDateMoved, txtZipCodeResidential});

        jTabbedPane1.addTab("Residential History", residentialHistoryJPanel);

        employmentHistoryJPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtCurrentEmployer.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtCurrentEmployer.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Current Employer");

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Job Title");

        txtJobTitleCurrent.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtJobTitleCurrent.setEnabled(false);

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Date of Employment");

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Previous Employer");

        txtPreviousEmployer.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtPreviousEmployer.setEnabled(false);

        txtJobTitlePrevious.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtJobTitlePrevious.setEnabled(false);

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Job Title");

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Date of Employment");

        btnPersonalInfoNext4.setBackground(new java.awt.Color(0, 0, 0));
        btnPersonalInfoNext4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnPersonalInfoNext4.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalInfoNext4.setText("Next>>");
        btnPersonalInfoNext4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoNext4ActionPerformed(evt);
            }
        });

        txtdatecurrent.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtdatecurrent.setEnabled(false);

        txtdateprevious.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtdateprevious.setEnabled(false);

        javax.swing.GroupLayout employmentHistoryJPanelLayout = new javax.swing.GroupLayout(employmentHistoryJPanel);
        employmentHistoryJPanel.setLayout(employmentHistoryJPanelLayout);
        employmentHistoryJPanelLayout.setHorizontalGroup(
            employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employmentHistoryJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel16)
                        .addComponent(jLabel26)
                        .addGroup(employmentHistoryJPanelLayout.createSequentialGroup()
                            .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addComponent(jLabel15)
                                .addComponent(jLabel27))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtJobTitlePrevious, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(txtCurrentEmployer)
                                .addComponent(txtJobTitleCurrent)
                                .addComponent(txtPreviousEmployer)
                                .addComponent(txtdatecurrent)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employmentHistoryJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtdateprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPersonalInfoNext4))
                .addContainerGap(681, Short.MAX_VALUE))
        );
        employmentHistoryJPanelLayout.setVerticalGroup(
            employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employmentHistoryJPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCurrentEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtJobTitleCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtdatecurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtPreviousEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJobTitlePrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employmentHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtdateprevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnPersonalInfoNext4)
                .addContainerGap(623, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Employment History", employmentHistoryJPanel);

        referencesJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Name");

        txtnamereference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtnamereference.setEnabled(false);

        txtRelationshipReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtRelationshipReference.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Relationship");

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Telephone Number");

        txtAddressReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtAddressReference.setEnabled(false);

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Address");

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("City");

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("State");

        txtCityReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtCityReference.setEnabled(false);

        btnDataSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnDataSubmit.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnDataSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnDataSubmit.setText("Process Request");
        btnDataSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataSubmitActionPerformed(evt);
            }
        });

        txtTelephoneReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtTelephoneReference.setEnabled(false);

        txtStateReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtStateReference.setEnabled(false);

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Zip Code");

        txtZipReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtZipReference.setEnabled(false);

        jLabel43.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 102, 102));
        jLabel43.setText("Country");

        txtCountryReference.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtCountryReference.setEnabled(false);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout referencesJPanelLayout = new javax.swing.GroupLayout(referencesJPanel);
        referencesJPanel.setLayout(referencesJPanelLayout);
        referencesJPanelLayout.setHorizontalGroup(
            referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referencesJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18)
                    .addComponent(jLabel31)
                    .addGroup(referencesJPanelLayout.createSequentialGroup()
                        .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtZipReference, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCountryReference, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStateReference, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addGroup(referencesJPanelLayout.createSequentialGroup()
                        .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel17)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAddressReference, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtTelephoneReference, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRelationshipReference, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnamereference, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCityReference)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, referencesJPanelLayout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDataSubmit)
                        .addGap(1, 1, 1)))
                .addContainerGap(626, Short.MAX_VALUE))
        );

        referencesJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel17, jLabel18, jLabel30, jLabel31, jLabel32, jLabel33, jLabel34, jLabel43});

        referencesJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDataSubmit, txtAddressReference, txtCityReference, txtCountryReference, txtRelationshipReference, txtStateReference, txtTelephoneReference, txtZipReference, txtnamereference});

        referencesJPanelLayout.setVerticalGroup(
            referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referencesJPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtnamereference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtRelationshipReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtTelephoneReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtAddressReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(txtCityReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStateReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtZipReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCountryReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addGap(28, 28, 28)
                .addGroup(referencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDataSubmit)
                    .addComponent(btnBack))
                .addContainerGap(549, Short.MAX_VALUE))
        );

        referencesJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel17, jLabel18, jLabel30, jLabel31, jLabel32, jLabel33, jLabel34, jLabel43, txtAddressReference, txtCityReference, txtCountryReference, txtRelationshipReference, txtStateReference, txtTelephoneReference, txtZipReference, txtnamereference});

        jTabbedPane1.addTab("References", referencesJPanel);

        jLabel44.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("View Foster Family Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jSeparator1)
            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setFields() {
        Map<String, String> personalInfo;
        Map<String, String> contactInfoMap;
        Map<String, String> residentialInfoMap;
        Map<String, String> employmentMap;
        Map<String, String> referenceMap;
        personalInfo = request.getPersonalInfoMap();
        contactInfoMap = request.getContactInfoMap();
        residentialInfoMap = request.getResidentialHistoryMap();
        employmentMap = request.getEmploymentHistoryMap();
        referenceMap = request.getReferenceMap();
        System.out.println("request is: "+personalInfo);
        txtFNameParent1.setText(personalInfo.get(PARENT1_FIRST_NAME));
        txtLNameParent1.setText(personalInfo.get(PARENT1_LAST_NAME));
        txtCitizenParent1.setText(personalInfo.get(PARENT1_CITIZENSHIP));
        txtParent1Gender.setText(personalInfo.get(PARENT1_GENDER));
        txtParent1BirthDate.setText(personalInfo.get(PARENT1_BIRTH));
        txtFNameParent2.setText(personalInfo.get(PARENT2_FIRST_NAME));
        txtLNameParent2.setText(personalInfo.get(PARENT2_LAST_NAME));
        txtCitizenParent3.setText(personalInfo.get(PARENT2_CITIZENSHIP));
        txtParent2Gender.setText(personalInfo.get(PARENT2_GENDER));
        txtParent2BirthDate.setText(personalInfo.get(PARENT2_BIRTH));
        
        txtEmail.setText(contactInfoMap.get(PARENT_EMAIL));
        txtPhone.setText(contactInfoMap.get(PARENT_PHONE));
        txtAddress1.setText(contactInfoMap.get(PARENT_ADDRESS1));
        txtAddress2.setText(contactInfoMap.get(PARENT_ADDRESS2));
        txtCity.setText(contactInfoMap.get(PARENT_CITY));
        txtState.setText(contactInfoMap.get(PARENT_STATE));
        txtZipCode.setText(contactInfoMap.get(PARENT_ZIPCODE));
        txtCountry.setText(contactInfoMap.get(PARENT_COUNTRY));
        
        txtmoved.setText(residentialInfoMap.get("movedcheck"));
        txtAddress1Residential.setText(residentialInfoMap.get(PARENT_OLD_ADDRESS1));
        txtAddress2Residential.setText(residentialInfoMap.get(PARENT_OLD_ADDRESS2));
        txtCityResidential.setText(residentialInfoMap.get(PARENT_OLD_CITY));
        txtStateResidential.setText(residentialInfoMap.get(PARENT_OLD_STATE));
        txtZipCodeResidential.setText(residentialInfoMap.get(PARENT_OLD_ZIPCODE));
        txtCountryResidential.setText(residentialInfoMap.get(PARENT_OLD_COUNTRY));
        txtDateMoved.setText(residentialInfoMap.get(ADDRESS_MOVED_ON));
        
        txtCurrentEmployer.setText(employmentMap.get(PARENT_CURRENT_EMPLOYER));
        txtJobTitleCurrent.setText(employmentMap.get(PARENT_JOB_TITLE));
        txtdatecurrent.setText(employmentMap.get(DATE_OF_CURRENT_JOB));
        txtPreviousEmployer.setText(employmentMap.get(PARENT_PREVIOUS_EMPLOYER));
        txtJobTitlePrevious.setText(employmentMap.get(PARENT_PREVIOUS_JOB_TITLE));
        txtdateprevious.setText(employmentMap.get(DATE_OF_PREVIOUS_JOB));
        
        txtnamereference.setText(referenceMap.get(REFERENCE_NAME));
        txtRelationshipReference.setText(referenceMap.get(REFERENCE_RELATION));
        txtTelephoneReference.setText(referenceMap.get(REFERENCE_PHONE));
        txtAddressReference.setText(referenceMap.get(REFERENCE_ADDRESS));
        txtCityReference.setText(referenceMap.get(REFERENCE_CITY));
        txtStateReference.setText(referenceMap.get(REFERENCE_STATE));
        txtZipReference.setText(referenceMap.get(REFERENCE_ZIPCODE));
        txtCountryReference.setText(referenceMap.get(REFERENCE_COUNTRY));
        
        
    }
    
    
    private void btnPersonalInfoNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoNextActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);

    }//GEN-LAST:event_btnPersonalInfoNextActionPerformed

    private void btnPersonalInfoNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoNext1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnPersonalInfoNext1ActionPerformed

    private void btnPersonalInfoNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoNext2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnPersonalInfoNext2ActionPerformed

    private void btnPersonalInfoNext4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoNext4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnPersonalInfoNext4ActionPerformed

    private void btnDataSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSubmitActionPerformed
        // TODO add your handling code here:
        PoliceProcessWorkRequestJPanel policeProcessWorkRequestJPanel = new PoliceProcessWorkRequestJPanel(userProcessContainer, request, account, organization, enterprise);
        userProcessContainer.add("PoliceProcessWorkRequestJPanel", policeProcessWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDataSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        PoliceWorkAreaJPanel policeWorkAreaJPanel = new PoliceWorkAreaJPanel(userProcessContainer, account,  organization,  enterprise);
        userProcessContainer.add("policeWorkAreaJPanel", policeWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDataSubmit;
    private javax.swing.JButton btnPersonalInfoNext;
    private javax.swing.JButton btnPersonalInfoNext1;
    private javax.swing.JButton btnPersonalInfoNext2;
    private javax.swing.JButton btnPersonalInfoNext4;
    private javax.swing.JPanel contactInfoJPanel;
    private javax.swing.JPanel employmentHistoryJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel personalInfoJPanel;
    private javax.swing.JPanel referencesJPanel;
    private javax.swing.JPanel residentialHistoryJPanel;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress1Residential;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtAddress2Residential;
    private javax.swing.JTextField txtAddressReference;
    private javax.swing.JTextField txtCitizenParent1;
    private javax.swing.JTextField txtCitizenParent3;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCityReference;
    private javax.swing.JTextField txtCityResidential;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtCountryReference;
    private javax.swing.JTextField txtCountryResidential;
    private javax.swing.JTextField txtCurrentEmployer;
    private javax.swing.JTextField txtDateMoved;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFNameParent1;
    private javax.swing.JTextField txtFNameParent2;
    private javax.swing.JTextField txtJobTitleCurrent;
    private javax.swing.JTextField txtJobTitlePrevious;
    private javax.swing.JTextField txtLNameParent1;
    private javax.swing.JTextField txtLNameParent2;
    private javax.swing.JTextField txtParent1BirthDate;
    private javax.swing.JTextField txtParent1Gender;
    private javax.swing.JTextField txtParent2BirthDate;
    private javax.swing.JTextField txtParent2Gender;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPreviousEmployer;
    private javax.swing.JTextField txtRelationshipReference;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStateReference;
    private javax.swing.JTextField txtStateResidential;
    private javax.swing.JTextField txtTelephoneReference;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JTextField txtZipCodeResidential;
    private javax.swing.JTextField txtZipReference;
    private javax.swing.JTextField txtdatecurrent;
    private javax.swing.JTextField txtdateprevious;
    private javax.swing.JTextField txtmoved;
    private javax.swing.JTextField txtnamereference;
    // End of variables declaration//GEN-END:variables

    
}
